development: &defaults
  adapter:  postgresql
  host:     <%= ENV['DATABASE_HOST'] %>
  port:     <%= ENV['DATABASE_PORT'] || 5432 %>
  database: pgsql_query_finder_development
  username: <%= ENV['DATABASE_USERNAME'] %>
  pool:     5
  timeout:  5000

test:
  <<: *defaults
  database: pgsql_query_finder_pay_test